# Generated by Django 3.2.4 on 2021-08-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='XP',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='courses_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='global_rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='info',
            field=models.TextField(default='N\\A', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='languages',
            field=models.TextField(default='N\\A', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(choices=[(0, 'Sleepy Baby'), (1, 'Basic Teen'), (2, 'Average Nerd'), (3, 'Script Kiddie'), (4, 'Hacker'), (5, 'Master')], default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='puzzles_completed',
            field=models.IntegerField(default=0),
        ),
    ]
