# Generated by Django 3.2.4 on 2021-06-07 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20210607_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 7, 23, 3, 13, 416589), verbose_name='date published'),
        ),
    ]
