# Generated by Django 3.2.4 on 2021-07-02 09:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20210608_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzle_category', models.CharField(max_length=200)),
                ('category_summary', models.CharField(max_length=200)),
                ('category_slug', models.CharField(default=1, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('published', models.DateTimeField(default=datetime.datetime(2021, 7, 2, 15, 10, 32, 537989), verbose_name='date published')),
                ('puzzle_slug', models.CharField(default=1, max_length=200)),
                ('puzzle_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.difficulty', verbose_name='Difficulty')),
            ],
        ),
        migrations.RemoveField(
            model_name='courseseries',
            name='course_category',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='CourseCategory',
        ),
        migrations.DeleteModel(
            name='CourseSeries',
        ),
    ]
