# Generated by Django 3.2.4 on 2021-07-02 11:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210702_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 16, 56, 4, 631836), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='puzzlesolution',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
