# Generated by Django 3.2.4 on 2021-07-02 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210702_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='answer',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 17, 4, 53, 110618), verbose_name='date published'),
        ),
    ]
