# Generated by Django 3.2.4 on 2021-07-02 11:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210702_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 2, 17, 6, 11, 28421), verbose_name='date published'),
        ),
    ]
