# Generated by Django 3.2.4 on 2021-08-13 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_puzzle_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 13, 15, 13, 5, 884844), verbose_name='date published'),
        ),
    ]
