# Generated by Django 3.2.4 on 2021-08-18 10:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_puzzle_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 16, 13, 58, 240488), verbose_name='date published'),
        ),
    ]
