# Generated by Django 3.2.4 on 2021-08-19 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_alter_puzzle_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='hint',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='starterCode',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='testCases',
            field=models.TextField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 21, 37, 20, 805077), verbose_name='date published'),
        ),
    ]
