# Generated by Django 3.2.4 on 2021-08-19 17:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_auto_20210819_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='hint',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 22, 45, 22, 528606), verbose_name='date published'),
        ),
    ]
