# Generated by Django 3.2.4 on 2021-08-19 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_auto_20210819_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='puzzleSolution',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 19, 22, 46, 51, 142847), verbose_name='date published'),
        ),
    ]
