# Generated by Django 3.2.4 on 2021-08-22 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_username'),
        ('main', '0049_auto_20210822_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='solvers',
            field=models.ManyToManyField(to='profiles.Profile'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 23, 50, 59, 167192), verbose_name='date published'),
        ),
    ]
