# Generated by Django 3.2.4 on 2021-08-22 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_username'),
        ('main', '0050_auto_20210822_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 23, 52, 23, 34685), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='solvers',
            field=models.ManyToManyField(default=None, to='profiles.Profile'),
        ),
    ]
