# Generated by Django 3.2.4 on 2021-08-22 18:25

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0051_auto_20210822_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 22, 23, 55, 11, 477780), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='solvers',
            field=models.ManyToManyField(related_name='Solves', to=settings.AUTH_USER_MODEL),
        ),
    ]
