# Generated by Django 3.2.4 on 2021-08-22 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20210822_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 0, 10, 40, 135006), verbose_name='date published'),
        ),
    ]
